### PR TITLE
Added dot product into stream.c and results obtained on Dmitry's machine.

### PR DESCRIPTION
**Pull request by dmdu**

### CODE REVIEW

**Comment by jedbrown** [comment]
Thanks!  Can you commit the source change that implements `Dot` and add it to this pull request?

**Comment by dmdu** [comment]
Updated now.

**Comment by dmdu** [comment]
Thanks for the feedback. Declared sum properly and now compiling using:  make CC=gcc CFLAGS='-O3 -march=native -DTUNED' stream 
I think I am using the reduction as it should be used. However, I am consistently getting 0 for the duration of the dot product calculation, and I am not entirely sure why.

**Comment by fdkong** [comment]
As Jed said yesterday, you should use the dot result 'sum' otherwise the compiler will automatically remove your code.

**Comment by jedbrown** [comment]
Thanks @fdkong. See also this mailing list reply. https://jedbrown.org/lists/archives/hpc-perf-analysis/2015-January/000000.html

**Comment by dmdu** [comment]
Thanks for these comments! I knew it was something funny like that because the code looked right. Do you still want us to push the updated stream.c or, since it has been merged already, should we add the results file only?

**Comment by jedbrown** [comment]
Push your version and I'll resolve conflicts in the merge. Also, if you worked with someone on the commit, please add a tag crediting them at the end of the commit message

```
Helped-by: Valuable Friend <friend@host.tld>
```

(`Reviewed-by` is also common.)

**Pull request merged**
